### ISSUE TITLE
「n月m日」のパースについて

### ISSUE THREAD

**Issue by ryooo** [sugi/wareki#9]
こういったパースをできるようになってもらえると、日本人的にありがたいと思うのですがいかがでしょう？
```ruby
irb(main):004:0> d = Date.parse("平成27年8月22日")
=> #<Date: 2015-08-22 ((2457257j,0s,0n),+0s,2299161j)>

irb(main):006:0> d = Date.parse("8月22日")
=> #<Date: 2019-03-22 ((2458565j,0s,0n),+0s,2299161j)>
=> 期待値は、2019-08-22
```
「年号」があれば正しくパースされるが、年号がないときに標準のDate.parseと同様に、現在月扱いになってしまう状況です。

年号がない時も以下と同様に「n月m日」のパースに対応してもらえるとありがたいと思います。
```ruby
irb(main):007:0> d = Date.parse("8/22")
=> #<Date: 2019-08-22 ((2458718j,0s,0n),+0s,2299161j)>
 ```

また、「n月m日」のパースに対応いただけるようでしたら、以下の月日が両方一桁のケースについても検討いただけると幸いです。
```ruby
irb(main):009:0> d = Date.parse("平成27年1月3日")
=> #<Date: 2015-01-03 ((2457026j,0s,0n),+0s,2299161j)>
=> 問題なし

irb(main):011:0> d = Date.parse("1/3")
=> #<Date: 2019-01-03 ((2458487j,0s,0n),+0s,2299161j)>
=> 問題なし

irb(main):010:0> d = Date.parse("1月3日")
Traceback (most recent call last):
        7: from /Users/ryooo/.rbenv/versions/2.6.0/bin/irb:23:in `<main>'
        6: from /Users/ryooo/.rbenv/versions/2.6.0/bin/irb:23:in `load'
        5: from /Users/ryooo/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):10
        3: from /Users/ryooo/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wareki-0.3.0/lib/wareki/std_ext.rb:27:in `parse'
        2: from /Users/ryooo/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wareki-0.3.0/lib/wareki/std_ext.rb:30:in `rescue in parse'
        1: from /Users/ryooo/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wareki-0.3.0/lib/wareki/std_ext.rb:30:in `parse'
ArgumentError (invalid date)
```
標準のDateではArgumentErrorになるのですが、日本語に特化したgemだと思いますのでいかがでしょう。

**Comment by sugi** [comment]
なるほどそれは確かに。
ちょっと来月になる予定ですが、変更しておきます。

**Comment by ryooo** [comment]
ありがとうございます。
PRの形となっておらず恐れ入ります 🙇

**Comment by sugi** [comment]
0.4.0 で対応しておきました。
